<?php

$current_level = "current_level";
$st_currentlevel = "st_currentlevel";
$level_aktif = "level_aktif";
$dbi = "dbi";
$namalengkap = "namalengkap";
$current_level = "current_level";
$btjugldt = "tanggal";
$namauser = "namauser";

require_once("clogin.php");
require_once("config/dbi_connect.php");

$namauser = $_SESSION["namauser"];
$namalengkap = $_SESSION["nama_lengkap"];
${$btjugldt} = date("Y-m-d");
$level_aktif = $_SESSION["leveluser"];
$current_level = mysqli_fetch_assoc(mysqli_query($dbi, "SELECT `urutan`, `level`, `alias` FROM `level` WHERE `level`='$level_aktif';"));
$st_currentlevel = $current_level["alias"];

echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "    <head>\n";
echo "        <meta charset=\"utf-8\">\n";
echo "        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n";
echo "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
echo "        <link rel=\"stylesheet\" href=\"bootsrap337/w3.css\">\n";
echo "        <link rel=\"stylesheet\" href=\"penyimpanan/penyimpanan.css\">\n";
echo "        <link rel=\"stylesheet\" href=\"bootsrap337/css/bootstrap.min.css\">\n";
echo "    </head>\n";
echo "    <style>\n";
echo "        .inputkantong{height: 40px !important;\n";
echo "        }\n";
echo "    </style>\n";
echo "    <body>\n";
echo "        <div class=\"container-fluid\" style=\"margin: 30px;\">\n";
echo "            <div class=\"row\">\n";
echo "                <div class=\"col-xs-12\">\n";
echo "                    <h4 class=\"w3-text-theme w3-\">Cek kantong/produk darah level <b>";
echo $st_currentlevel;
echo "</b></h4>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "            <div class=\"row\">\n";
echo "                <div class=\"col-xs-12\">\n";
echo "                    <form name=\"FrmKantong\" id=\"FrmKantong\" action=\"\" method=\"POST\">\n";
echo "                        <div class=\"panel w3-border-theme\">\n";
echo "                            <div class=\"panel-heading w3-theme-d5 clearfix w3-card-4\" style=\"height:60px;\">\n";
echo "                                <div class=\"col-xs-12 col-sm-8 col-md-6 text-left\" style=\"font-size: 120%;font-weight: bold;\">\n";
echo "                                    <div class=\"form-group\" style=\"max-width: 320px;\">\n";
echo "                                        <div class=\"input-group inputkantong\">\n";
echo "                                            <span class=\"input-group-addon w3-theme-l4 inputkantong\">Barcode</span>\n";
echo "                                            <input id=\"InpBarcode\" name=\"InpBarcode\" type=\"text\" class=\"form-control inputkantong\" placeholder=\" Nomor kantong\" autofocus autocomplete=\"off\" required>    \n";
echo "                                            <span class=\"input-group-btn\">\n";
echo "                                                <button type=\"submit\" id=\"SubmitScanBarcode\" name=\"SubmitScanBarcode\" class=\"btn w3-theme-l1 w3-hover-yellow inputkantong\"><i class=\"glyphicon glyphicon-compressed\"></i></button>\n";
echo "                                            </span>\n";
echo "                                        </div>\n";
echo "                                    </div>\n";
echo "                                </div>\n";
echo "                                <div class=\"pull-right\">\n";
echo "                                    <div id=\"tload\" style=\"display: none;\"><img src=\"profile/simdondar_loading1.gif\"></div>\n";
echo "                                </div>\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "                    </form>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "            <div class=\"infokantong\"></div>\n";
echo "            <div class=\"row\">\n";
echo "                <div class=\"col-sm-12 text-center\">\n";
echo "                    <div id=\"barcodetmp\" style=\"display: none\"></div>\n";
echo "                    <div id=\"tload1\" style=\"display: none;\"><img src=\"profile/simdondar_loading1.gif\"></div>\n";
echo "                    <button type=\"button\" class=\"w3-btn w3-white w3-border w3-border-red w3-round-large w3-card w3-hover-theme\" id=\"btndetail\" style=\"display: none;\"> Tampilkan lebih detail <span class=\"glyphicon glyphicon-list-alt\"></button>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "            <div class=\"infokantongdetail\"></div>\n";
echo "        </div>\n";
echo "        <!-- Modal Info Kantong Terkait -->\n";
echo "        <div class=\"modal fade\" id=\"MInfoTerkait\" role=\"dialog\">\n";
echo "            <div class=\"modal-dialog modal-lg\" role=\"document\">   \n";
echo "                <div class=\"modal-content\">\n";
echo "                    <div class=\"modal-header w3-theme-d5 w3-card-4\">\n";
echo "                        <h4 class=\"modal-title\" style=\"color:white;\">Informasi kantong </h4>\n";
echo "                    </div>\n";
echo "                    <div class=\"modal-body\">\n";
echo "                        <div id=\"mtload\" class=\"text-center\"><img src=\"penyimpanan/images/rubix.gif\" style=\"height: 200px;\"></div>\n";
echo "                        <div class=\"modal-data\"></div>\n";
echo "                    </div>\n";
echo "                    <div class=\"modal-footer\">\n";
echo "                        <button class=\"w3-btn w3-theme-d4 w3-hover-red w3-card\" data-dismiss=\"modal\">Tutup</button>\n";
echo "                    </div>\n";
echo "                    </form>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "    </body>\n";
echo "</html>\n";
echo "<script src=\"bootsrap337/js/jquery.min.js\"></script>\n";
echo "<script src=\"bootsrap337/js/bootstrap.min.js\"></script>\n";
echo "<script>\n";
echo "    \$(document).ready(function () {\n";
echo "        \$('#InpBarcode').focus();\n";
echo "        \$(\"#FrmKantong\").submit(function (event) {\n";
echo "            var jbarcode=\$('#InpBarcode').val();\n";
echo "            \$('#barcodetmp').text(jbarcode);\n";
echo "            \$('#btndetail').hide();\n";
echo "            \$.ajax({\n";
echo "                type    : 'POST',\n";
echo "                url     : 'penyimpanan/cek_kantongajax.php?mode=1',\n";
echo "                data:\$(\"#FrmKantong input\").serialize(),\n";
echo "                beforeSend:function(){\n";
echo "                    \$('.infokantong').html('');\n";
echo "                    \$('.infokantongdetail').html('');\n";
echo "                    \$(\"#tload\").show();\n";
echo "                },\n";
echo "                success: function (data) {\n";
echo "                    ex_data=data.split('|');\n";
echo "                    \$('.infokantong').html(ex_data[0]);\n";
echo "                    if(ex_data[1]==\"1\"){\n";
echo "                        \$('#btndetail').show();\n";
echo "                    }\n";
echo "                },\n";
echo "                complete:function(){\n";
echo "                    \$('#tload').hide();\n";
echo "                    \$('#InpBarcode').val('');\n";
echo "                    \$('#InpBarcode').focus();\n";
echo "                }                   \n";
echo "            });\n";
echo "            event.preventDefault();\n";
echo "            return false;\n";
echo "        })\n";
echo "        \$('#btndetail').on('click', function(event) {\n";
echo "            var jbarcode = \$('#barcodetmp').text()\n";
echo "            event.preventDefault();\n";
echo "            \$('#btndetail').hide();\n";
echo "            \$.ajax({\n";
echo "                type    : 'POST',\n";
echo "                url     : 'penyimpanan/cek_kantongajax.php?mode=2',\n";
echo "                data    : 'InpBarcode='+jbarcode,\n";
echo "                beforeSend:function(){\n";
echo "                    \$('.infokantongdetail').html('');\n";
echo "                    \$(\"#tload1\").show();\n";
echo "                },\n";
echo "                success: function (data) {\n";
echo "                    ex_data=data.split('|');\n";
echo "                    \$('.infokantongdetail').html(ex_data[0]);\n";
echo "                    \$('#tload1').hide();\n";
echo "                    \$('#InpBarcode').val('');\n";
echo "                    \$('#InpBarcode').focus();\n";
echo "                }\n";
echo "            })\n";
echo "        });\n";
echo "    })\n";
echo "    \$(\"#MInfoTerkait\").on(\"hidden.bs.modal\", function(){\n";
echo "        \$(\"#MInfoTerkait .modal-data\").html(\"\");\n";
echo "        \$('#mtload').show();\n";
echo "        \n";
echo "    });\n";
echo "\n";
echo "    \$('#MInfoTerkait').on('shown.bs.modal', function (e) {\n";
echo "            let jnokantong = \$(e.relatedTarget).attr('data-id');\n";
echo "            \$('#MInfoTerkait .modal-title').html('Informasi kantong: '+jnokantong);\n";
echo "            \$(\"#MInfoTerkait .modal-data\").html(\"\");\n";
echo "            \$('#mtload').show();\n";
echo "            \$.ajax({\n";
echo "                type    : 'POST',\n";
echo "                url     : 'penyimpanan/cek_kantongajax.php?mode=3',\n";
echo "                data    : 'InpBarcode='+jnokantong,\n";
echo "                success : function(data){\n";
echo "                    ex_data=data.split('|');\n";
echo "                    \$('#mtload').hide();\n";
echo "                    \$(\"#MInfoTerkait .modal-data\").html(ex_data[0]);\n";
echo "                }\n";
echo "            });\n";
echo "        });\n";
echo "</script>\n";